### ISSUE TITLE
Editor Markdown regex fails with text directly after tags

### ISSUE THREAD

**Issue by wip-abramson** [WebOfTrustInfo/satyrn#10]
This works and renders and editor
```javascript
console.log("Hey! 1")
```

But this fails to render the editor
```javascript
console.log("Hey! 1")
```sometext

Just want to capture this.

**Comment by jandrieu** [comment]
Labelled as Nice to have because it's easy to see and work around. We can ship with it.

**Comment by jandrieu** [comment]
Let's flag this as 1.1 as it *will* break on markdown from the wild.
