### ISSUE TITLE
On reload, the edit mode got inverted

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#13]
I was editing and the rendered content went blank--and devtools couldn't attach. (Not yet reproducible, so that's not yet an issue on Github).

I successfully reloaded from the development menu. (We should move that to the file menu.)

That worked. But the "edit mode" entry in the file menu was out of sync. The content loaded into non-edit mode (which is correct), but the menu wasn't updated. So on load/reload, we should reset the state of the menus. It was fun that selecting the edit mode in the menu toggled edit mode correctly, it was just now out of sync.

**Comment by wip-abramson** [comment]
Should be fixed
