### ISSUE TITLE
Real Time Render Functionality

### ISSUE THREAD

**Issue by wip-abramson** [WebOfTrustInfo/satyrn#14]
@jandrieu I have added the ability to turn off real time rendering of markdown.

Need to decide where and how this should work.
Eg.
Should this be visible in production?
Should this just be a feature of edit mode? If so how does someone render? - Save possibly?
What should we name the menu item? 
Which menu should it go under?

**Comment by wip-abramson** [comment]
@jandrieu

**Comment by jandrieu** [comment]
Maybe a checkbox for Render realtime? Only shown on edit.
And, yes, always render on save.

**Comment by jandrieu** [comment]
I made this MVP because I was getting crashes from the rendering process.

**Comment by wip-abramson** [comment]
I have added the checkbox for this. @jandrieu you mentioned some shortcut to render without saving, how do you imagine this working?

**Comment by wip-abramson** [comment]
Move checkbox to file menu. On toggle real time render then render the document
