### ISSUE TITLE
Styling for about & guide pages

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#17]
So, I realized jamming stuff into the default.md wasn't working for me. So I created a help menu with an about page and a guide page. 

I then used the .md converter so we could write those pages in .md, and display in a new window.

I mostly have it working, except that the menus are getting attached to our popup and the styling sucks.

I tried forcing the use of the native chrome window open by setting a field in webPreferences, but that didn't work. I'm hoping somewhere in there we can check the window before attaching the menu. That code looked a bit out of order to my mental model for how that would work, so I didn't muck with it.

Similarly, I'm just jamming the showdown into a new html page without any wrapping context or styling. So it looks kinda janky. We probably want to load up main.css at a minimum, perhaps with some simple boilerplate html to put the converted markdown.

So two things for the new popups (about and guide)
- [ ] get rid of menus 
- [x] restore decent html styling

**Comment by wip-abramson** [comment]
What do you mean by get rid of menus?

**Comment by jandrieu** [comment]
If you open the about or guide (from the help menu), the resulting pop-up window has the menu bar from the main application. Ideally, it would just be a bare window with a close box (which happens to close when we close the app).

**Comment by jandrieu** [comment]
Two things:
1. The menu set appears to be some "default" rather than no menu. Maybe replace with a simple menu that just has "close".

2. The css for ACE editors in the Guide page is different than what's in the main page.

**Comment by jandrieu** [comment]
Let's rename Guide to Tutorial.

**Comment by jandrieu** [comment]
Closing as we've forked to separate issues, with different MVP/nice-to-have status
