### ISSUE TITLE
Add status bar with hover for URLs

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#18]
Yet another feature I take for granted in Chrome. Hovering over links tells you what the link is.

Hopefully this is a generalizable thing to support hover functionality in .md files.

**Comment by ewelton** [comment]
Greetings from the jungle (and a bit of a haze from travel - last I slept was Monday night in Barcelona - ouch)

I'd never really given the hover-over a thought - always just assumed it was a standard library from the client side, never thought that it was browser based.

Given that electron is Chromium - maybe it is a easy reach?  I love it when I get a little context to pop up just by hovering over something.
