### ISSUE TITLE
develop overview?

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#20]
Could one of you write a quick explanation about where different pieces of the code live?

In particular, I added a help and about page. Adding the menu was straight forward, and I just pass an event to the renderer. But once I get over there, I'm not sure if it should go directly in app.js or if I should put it in helpers and call a higher level function from app.s (I think that's what I should have done).

Ideally, this is SUPER lightweight... just a few sentences explaining how the code is organized, without being too hard to maintain.

**Comment by ewelton** [comment]
the jupyterlab app has two folders "browser" and "main" - this is clearer to me than "app.js" and "background.js"

browser/* runs in a renderer
main/* runs the host process (OS bindings, menus, etc.)

not too crazy about the name 'main' - but something along that line - "headless app that deals with OS-based singletons" and "the many faces of the hydra" - we could, perhaps split browser out into multiple types as well, if we wanted - like "quick help viewer" and "editable notebook" - but that's secondary.

+10 on taking steps to clear up "what runs where"

**Comment by wip-abramson** [comment]
Yes I agree. Currently we have just been putting everything in app. This could do with a good refactor when we have decided how we should be doing things.

Only think I have been writing separately is the extensions.

**Comment by jandrieu** [comment]
Ok. This is a great start. Maybe we start a contributing.md file?

**Comment by wip-abramson** [comment]
Yep, I can kick one off. We also need to decide what we are going to do about testing.
