### ISSUE TITLE
Asynchronous & long running functions

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#23]
In the MVP, we are limiting our active support for immediate response functions.

However, we will need to work through how to pass appropriate console targets so that long-running asynchronous javascript methods can run and output can reasonably be directed to the associated console div. I still see that as ONLY maintaining the console & error output, NOT automatically doing any other IPC kinds of things. 

If a user really wants to, they can spin up a socket or http endpoint, even within a code section, but we don't do anything other than maintaining the process. FWIW, this is a must-have, just not MVP. When interacting with blockchain stuff, the delays to verify or post transactions can be significant, so its pretty vital for our catalyzing use case.

Let's discuss how we might do that.

My initial thought is that each code block is always executed with a custom console.log function, which directs the output to the correct div. That function should continue to work even when other code blocks are executed. 

Note that all code blocks will/should share the same compute context and hence, could block each other. That's just standard node/js stuff.

**Comment by jandrieu** [comment]
Btw, in this case, I can easily see separate sections that each spin up a long-running asynchronous function, with suitable console output directly below that code block, then students can run code that pings against those processes externally.

If you mess it up, you can reload. If you want to exclude some sections from execution,that should be easy (see #12) 

Actually, that sounds like an awesome way to build out microservices.

**Comment by ewelton** [comment]
Here is the core of the Jupyter javascript kernel - it's worth looking at for architecture suggestions

https://www.npmjs.com/package/jp-kernel

and it really comes down to this file:

https://github.com/n-riesco/jp-kernel/blob/master/lib/jp-kernel.js

I think this is an example of the 2nd landing point after the MVP.  In fact, we can give satyrn notebooks a mime type and then they can be fully integrated in the jupyter ecosystem as well as in our own viewer.

If we follow this pattern, we also get an API that supports all of our needs, and we get a javascript runtime out of the box.

In essence:
Stage 1: MVP => electron managed subprocess linked to an open doc.  subprocess coupling is via stdin/stdout/stderr, using the out-of-the-box event model from node's child_process package.

Stage 2:Replace the stdin/stdout/stderr model with a kernel adapter, which handles the features we need - we just need to connect it to our UI.  If we package up our satyrn notebooks in a mime-type and provide a React component (the browserWindow application) you've got something particularly powerful:
a) a re-usable UI that can participate in an existing ecosystem
b) a desktop educational app tailored to and directly supporting a specific, known, userbase (the RWoT, MyData, IIW, DIF, SSI, jada jada community of which we are members)

The reason to separate them into stages is the devops overhead of the build in switching to case 2 - we need solid control over the build-and-distribute pipeline, and while that is straightforward, it takes a while to spin up, Stage 2 is really about stabilizing that against a relatively mild, but deep, formalization of the UI / kernel relationship.

BTW - i recommend calling the sub-processes Kernels - here is the definition from Jupyterland: A notebook kernel is a “computational engine” that executes the code contained in a Notebook document  multi-kernel support is under active development - e.g. connecting to different engines w/in the space of a single document.  The challenge is mostly the UX of managing that relation - and shifting from a "document peers w/ engine" model to "document peers w/ engine-map"

it is also worth noting that ZMQ is pretty well positioned to bind into DID-based connection - and that makes this whole model feel a *lot* like Agents - which is pretty cool.  An opportunity for a bit of dogfooding for the broader community w/o blocking progress.

but first Stage 1! ;)
then some armor plating of the CI/CD pipeline (i suspect driven by the need to use gyp - although it would be nice to avoid that step)
