### ISSUE TITLE
Save from JS to markdown

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#24]
We talked about this on the call, in the context of the markdown author wanting to save edits made in the JS editor into the markdown.

I think this may be even more relevant for students.

So, I'm a student. I just spent three hours working through an exercise. I'd like to save my progress. How do I do that?

And how do I send a completed exercise to a teacher?

So... in addition to a way to save from the js editors to the markdown editor when in edit mode, we really want a way to be able to do that even if the student is not in "edit mode".

After kicking it around a bit, I think we should just ALWAYS update the markdown when editing the JS. The user can decide whether or not they want to save the resulting markdown, but requiring an extra step by the user to export from one to the other doesn't seem to make sense.

I'm tempted to disable "Save" but enable "Save As" when Edit mode is of and there are unsaved changes. This would help prevent students from accidentally overriding their source material, without too much of a burden to work around it if they really wanted to. Turning on edit mode or saving over the original file are all accessible options.

**Comment by wip-abramson** [comment]
My vote would be target this for 1.1, definitely a useful and expected feature

**Comment by wip-abramson** [comment]
This seems harder than I first thought. Possibly I am not thinking about it right. Lets discuss in the call today.
