### ISSUE TITLE
Suggestion : set up electron-log in lieu of console.log internally

### ISSUE THREAD

**Issue by ewelton** [WebOfTrustInfo/satyrn#27]
Move away from console.log to electron-log w/ a console and file target.

Electron has a logging package that lets you combine window logging and process logging using standard modern logging models.  There's some nice boilerplate we can apply and do the change pretty quickly.  Logs heavy - (the log level is 'silly') in development mode and restricted to 'error' in production.

This is a nice-to-have if we get consensus - so far the developer experience impact is using log.info() or log.warn() instead of console.log.

**Comment by jandrieu** [comment]
Yes, please.
