### ISSUE TITLE
New JavaScript editors no longer compute output in correctly

### ISSUE THREAD

**Issue by wip-abramson** [WebOfTrustInfo/satyrn#29]
When you add a new JavaScript tag and write code in the editor e.g. console.log("hello") no output is rendered when you run it. It seems to have an effect on previous editors if you go back and run one after you get some weird output.

Refresh is still works in new editors though.

I noticed this while testing a new window opened from a link but it is present in initial page too.

@ewelton guessing you might know the fix best.

**Comment by jandrieu** [comment]
Console.log last line (from ace editor) out of sync. Works if editing in markdown.

But when you run from the Ace editor, the last console.log

**Comment by jandrieu** [comment]
Ok. We fixed this by checking for EOL. @gannan08 noticed that without an extra line in the editor, it failed, but with it, it worked. So we added a check and append.

**Comment by wip-abramson** [comment]
Nice!
