### ISSUE TITLE
Satyrnicon.js?

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#32]
Naming is famously hard, but there's got to be a better name for this file.

It claims
```
// This handles the state of a single notebook document.
const satyrnicon = {
```

When I saw that name, i thought it was somehow generating the icon file used to represent Satyrn.

sandbox, perhaps?

**Comment by ewelton** [comment]
5555 - Icon.... i didn't notice that.

It's actually a play on https://en.wikipedia.org/wiki/Satyricon during chat around the table in Barcelona - but agreed, we should change it.

It represents the renderer state.  sandbox works fine for me - as in "the state of the active sandbox", including editors, editor ids, evaluation state, editor history (the restore button), etc.

**Comment by jandrieu** [comment]
LOL. That's awesome. I didn't get the reference at all.

**Comment by jandrieu** [comment]
We still have satyrnicon references in the kernel.js file

**Comment by wip-abramson** [comment]
Removed these now. Changed to state, seems good.
