### ISSUE TITLE
Bundle supporting files appropriately

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#40]
We currently have a bug because the default.md isn't bundled. Other assets need to come along too.

**Comment by wip-abramson** [comment]
Okay so this now works I think, needs testing on other OS

**Comment by wip-abramson** [comment]
Actually, its a bit weird on linux. We can review next Monday

**Comment by wip-abramson** [comment]
Actually, its a bit weird on linux. We can review next Monday

**Comment by jandrieu** [comment]
I added an issue at Electron-Builder
https://github.com/electron-userland/electron-builder/issues/3889

It appears that the icon path is not being quoted, leading to problems on Windows. For now, you may need to comment out the icon spec to get it to build a release.

**Comment by wip-abramson** [comment]
I have added a mac build config - someone to test.

When I build for linux I don't see the logo either.
