### ISSUE TITLE
Update electron to 5.0.1 or greater

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#42]
We should double check the interwebs to see if other folks have complained about it, but otherwise, I'd like to get to the new architecture before we go much further.

**Comment by wip-abramson** [comment]
I have bumped version to v5, ment to push to separate branch but didn't (sorry)

Only issue I haven't been able to solve is the executing of code no longer seems to work. Could someone else take a look into this?

I hope it is just missing some config.

**Comment by wip-abramson** [comment]
The listener in kernel.js line 28 seems not to be fired anymore

**Comment by wip-abramson** [comment]
https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md

**Comment by jandrieu** [comment]
We also fail to reload correctly. I just edited kernel.js and electron attempted to reload, but nothing happened. =( Just a blank page. No errors.

**Comment by wip-abramson** [comment]
Yep reload is a bit weird in this situation because it is electron-reload that initiates the reload so doesn't know where to get the page from. If you ctrl-r after it will reload the correct page. Figured this is okay since only a problem for devs. I'll take another look at it though.

**Comment by jandrieu** [comment]
The breaking changes to require seem to be applicable to build/start.js.

I'll try the suggested fix.

**Comment by wip-abramson** [comment]
Yep, missed that. There are also some in kernel & app

**Comment by wip-abramson** [comment]
Yep, missed that. There are also some in kernel & app

**Comment by jandrieu** [comment]
Ok. the one in build/start.js is not a rendering sandbox, so the work around actually triggered an error. I swapped the others to no effect. =(

**Comment by wip-abramson** [comment]
I also have had no luck. For some reason the run function in kernel.js no longer causes a data event to be fired. 
Shall we give it another week, if no luck lets just revert back to the older version that works.

**Comment by jandrieu** [comment]
> If a call to stream.write(chunk) returns false, the 'drain' event will be emitted when it is appropriate to resume writing data to the stream.

In kernel.js:run, we have 
> this.proc.stdin.write(code);

This write is returning false.

So... the child process is either not getting set up correctly, or the stdio is broken somehow. I'm unfamiliar with the cork/uncork method, but I'll keep digging. 

@ewelton Any clues?

**Comment by jandrieu** [comment]
Wow. That was annoying.

FWIW,  I tried a ton of things.
* that stdin.write NEVER returns true (with a setTimeout to retry forever in case fails).  
* We *do* get a "drain" event, but that doesn't seem to change anything.
* I thought it might be because NODE integration is disabled:
> nativeWindowOpen
> Child windows opened with the nativeWindowOpen option will always have Node.js integration disabled.

But that isn't it. In fact, setting nodeIntegration to false will cause the app to fail because it doesn't understand require. So... the integration is there, it's just not getting anything back from STDOUT.

* Node spins up just fine. 
* Messing with the highWaterMark values with let the write return true, but that doesn't help.

The answer was just to remove the "readable" event handler. That was **forcing** a buffer that we then were failing to read.

FWIW, I also think this is why my attempts at using "fork" didn't work. I'll revisit that.

Meanwhile, I think v5 is working.

Please test.

**Comment by wip-abramson** [comment]
Nice one!

All tested and works as before. I then ran a build though, which hangs on this command:

`> electron-mocha temp/specs.js --renderer --require source-map-support/register`

Sorry for saying.

**Comment by wip-abramson** [comment]
Actually I just bumped the versionof electron-mocha and seems to be working.

**Comment by jandrieu** [comment]
Progress!
