### ISSUE TITLE
Clean default.md file

### ISSUE THREAD

**Issue by wip-abramson** [WebOfTrustInfo/satyrn#46]
How do we want the initial start page of the application to look?

**Comment by wip-abramson** [comment]
Move to default.md to test.md. Put it in the repo but don't bundle. Have default.md a blank markdown.

**Comment by jandrieu** [comment]
Ok. I've stripped out a bunch from default.md.

I'm hesitant to delete EVERYTHING without a pop-up the first time its run. 

Or maybe a "home page" that is loaded. That would be more like how browsers work. We would just need a "home page" that does what we want.

Btw, did we get rid of the linked files with "_satyrn" opening in the same window?

**Comment by jandrieu** [comment]
Closing. I'll add another issue with home page ideas.
