### ISSUE TITLE
Add Icon to Bundle, Render in Application

### ISSUE THREAD

**Issue by wip-abramson** [WebOfTrustInfo/satyrn#47]
This is an issue in electron-builder

See https://github.com/WebOfTrustInfo/satyrn/issues/40  for details,

**Comment by jandrieu** [comment]
In package.json, in the build.win/mac/linux sections, we can specify an icon.
```json
"win": {
      "target": "zip",
      "icon": "logos/favicon/Favicon.ico"
    },
    "linux": {
      "target": "tar.gz",
      "icon": "logos/favicon/Favicon.ico"
    },
    "mac": {
      "target": "dmg",
      "icon": "logos/favicon/Favicon.ico"
    }
```

However, that fails on Windows because of a escape problem. We've deleted it from the package.json for now.

**Comment by HarounAns** [comment]
hey, did you ever figure out a work around? I'm getting the same error labeled "Unable to set icon image type is not icon for 'C'" for electron builder on windows. Did you come up with a solution to this problem?

**Comment by jandrieu** [comment]
I did not. Somewhere in the code, the path is being constructed poorly. I'm just not sure where.
