### ISSUE TITLE
Support for Edit and Develop modes

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#5]
We've had a couple of features proposed and even partially implemented. I'd like to propose 3 modes to support in the MVP.
* Sandbox (default, always on)
* Edit 
* Develop

These modes are not exclusive. You may simultaneously have both Edit and Develop features on and you can'd disable the sandbox.

# Default Mode - Sandbox
In this mode, the markdown is not editable, nor is the raw markdown visible. 

## file management features
* load file
* reload the current file
* "open with" from OS?

## sandbox features
* scroll through a single markdown file
* edit JavaScript source blocks
* run JavaScript blocks, with output to inline console
* refresh/reload JavaScript blocks
* resize JavaScript source blocks
* resize console blocks

## edit features (in edit menu, NOT the "Edit Mode"
* Undo
* Redo
* Cut
* Copy
* Paste

# In Edit mode (formerly Teacher mode)
In addition to all Sandbox and Develop features
## file management features 
* save markdown file
* save as markdown file

## edit features
* ACE editor for source code
  * syntax highlighting, etc., (from ACE configuration, not new features)
  * different theme for source code than from sandbox 
* Live updates to markdown

# Develop mode
These features are in addition to Sandbox and Edit features.
* live reload when files change (how do we toggle this on / off?)
* develop menu
   * Toggle dev tools

# Menu impact
I'm suggesting we add menu items to the "File menu"
* Edit Mode
* Develop Mode
With a checkbox indicating which modes are active.

# Future features 
These are ideas that came up that I just want to record for future roadmap
* Help (pops up HTML page?)
* Print
* Export 
  * as HTML (without bundling)
  * as HTML bundled
* live links in markdown
* email links in markdown
* load multiple files
* element highlighting (mouse-hover highlights element in dev window) in develop mode
* Glossary/definition links live in markdown (this may already be possible, do anchor tags work? I bet we don't scroll...)

**Comment by wip-abramson** [comment]
Should it be possible to go into develop mode without being in edit mode?

**Comment by jandrieu** [comment]
Yes. I'd like them to be independently activatable.

And as we discussed just now, we might want to find a way to disable develop mode when in "release" versions. So that you only get the develop mode tools if you've run from 'npm start'

**Comment by ewelton** [comment]
one option is to use the env switch.
 
i believe when you run "npm release" and build the app for distribution, it will run in "env=production" which would disable the develop model support completely.  In this way
- running from a distributed app by clicking on the app => no develop
- running from npm start defaults to develop mode (but can be forced to production mode for testing)

**Comment by wip-abramson** [comment]
Yep shouldn't be a problem. 

@jandrieu save functionality is now pushed.

**Comment by wip-abramson** [comment]
Do we need a toggleDevTools and a develop mode? 
Could develop mode go under the development menu?

**Comment by ewelton** [comment]
That's a good question - does "electron-reload" automatically disable if "env != production" by any chance?  If so, then maybe we don't really need to do anything to support develop mode.  Building for release would disable the electron-reload module and 'toggle Dev Tools' would just always be available.  Is there any reason to 'disable' the ability to open devtools when building for release?

**Comment by wip-abramson** [comment]
I have disabled electron-reload for production build.

**Comment by jandrieu** [comment]
> Do we need a toggleDevTools and a develop mode?
> Could develop mode go under the development menu?

Sure. That's a good idea.

**Comment by ewelton** [comment]
is there anything else on the development menu?
is it possible to toggle dev tools in production mode?

**Comment by jandrieu** [comment]
Hmmmmm

That's a good question.

Can we keep the accelerator without showing it on a menu?

**Comment by wip-abramson** [comment]
Removed develop mode, added shortcut to each window to toggle dev tools. 

I think this covers all we discussed for the issue.

**Comment by jandrieu** [comment]
Perfect. CTRL-SHFT-J FTW
