### ISSUE TITLE
Saturn Tutorial for Default.md

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#6]
I'll update the default.md as a "tutorial" introduction.

Any thoughts/comments/suggestions appreciated.

For example, I already verified that there's an easy way to link within the markdown, e.g. for glossary terms. That's a SUPER awesome feature for educational material, so I want to give examples of things like that.

Also, if we can show how to use a "local" node_module that might be good too, perhaps in a separate file.

**Comment by jandrieu** [comment]
A draft of this is now in "Guide".

So... let's clean up default.md when we are ready to ship. We can put content there in the "test" dialog box #36 

@wip-abramson @gannan08 @ewelton Please take a look at the "Guide" (which might be renamed to Tutorial by the time you get to it) in the Help menu, and provide feedback. It's a good stab, but I ran out of steam.

**Comment by wip-abramson** [comment]
Tutorial need to cover from initial user seeing the blank page of the application.

**Comment by jandrieu** [comment]
Ok! There is a draft for this.

I am missing a section on editing (explaining that there's a mode that lets you edit), but its a solid draft. Good enough for MVP, IMO.
