### ISSUE TITLE
Differences in loaded v edited URLs

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#8]
So... I added an explicit URL HTML tag in the default.md and it got weird.

When editing, it was properly parsed and became a link.

But when loading, it didn't render properly. If I then type just a modest amount, the rendering gets fixed.

So there's something weirdly different between the realtime rendering and the rendering on load...

**Comment by wip-abramson** [comment]
Hmm its weird but I have a quick fix that I think is okay. I added handleTextChange() to ipc open-file stuff.
