### ISSUE TITLE
URLs in document should open in a new window unless local references

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/satyrn#9]
So...

I added the link to Satyrn's repo and then clicked on it.

And we opened in the markdown window, which I think we don't want (We aren't trying to replace their browser for browsing).

I'm not 100% sure the best way to deal with it.  Perhaps.
1. for local references we do nothing (they should act like they do now)
2. for references without a target attribute should get target="_blank" when rendered.
3. for references with a target attribute are unchanged
4. to allow authors to explicitly load a new URL into the same Saturn context, we should open/name the current target context as "satyrn" so that it isn't hard for markdown editors to say "load it this url in Saturn". By which I mean, target="satyrn" opens in our app explicitly.

Btw, that last bit also makes it an interesting possible integration with web browsers to pass a URL reference from the web to our app. That's not a feature we want to worry about now, but whatever our solution, I'd like it to be the simplest & least breaking when using markdown from "the wild".

**Comment by ewelton** [comment]
i think that's reasonable all around - i only wonder about allowing *any* external document to open internally - as that adds a can of worms.... e.g. if there are changes in the document, do we also prompt for saving, etc.   so +1 for 1-3, but let's be certain about 4.

thoughts?

**Comment by wip-abramson** [comment]
So I tried target="_blank", That opens a new electron window, is that what we are expecting? Don't we want to open the link in their browser.

**Comment by jandrieu** [comment]
Hmph.

Yes. But now I'm not sure how to do that now. Maybe we need to intercept the open URL and launch a process with whatever the default browser is?

**Comment by jandrieu** [comment]
https://stackoverflow.com/questions/32402327/how-can-i-force-external-links-from-browser-window-to-open-in-a-default-browser

**Comment by ewelton** [comment]
I think so - like this, yes?
1 - in-doc links stay w/in window
2 - in-app links behave like target=_blank
3 - exsternal links are replaced with JS that runs a new browser

**Comment by jandrieu** [comment]
the new-window trick in the stack-overflow seems to be the right approach for 3.

*AND* we have to add the target="_blank" to all URLs without a target in the showdown extension.

**Comment by wip-abramson** [comment]
> https://stackoverflow.com/questions/32402327/how-can-i-force-external-links-from-browser-window-to-open-in-a-default-browser

I quickly tried this and it does open in browser but also in electron app. preventDefault() isn't doing what I would expect

**Comment by ewelton** [comment]
cool - tapping that event is nice - great find!  assuming we can figure out the preventDefault problem.

can you clarify the point about adding target=_blank.... not sure I follow

**Comment by jandrieu** [comment]
oh... 

I mispoke.

We'll need to process the markdown on load to change all URLs, not just the custom extension.

**Comment by jandrieu** [comment]
although I'm curious how we name the current context as "satyrn" so that target="satyrn" replaces the current content.

**Comment by ewelton** [comment]
Ah.... 
Is it possible to open a new satryn window?

**Comment by jandrieu** [comment]
currently, target="_blank" opens a new Satyrn window. But maybe we should offer that in a menu.

**Comment by jandrieu** [comment]
I got the basics of the opening in new window working on _blank targets.  I have not done the regex to replace all the missing external URLs to _blank.

**Comment by wip-abramson** [comment]
Nice. So what we really want is to part the markdown for 

[Rebooting the Web of Trust](http://weboftrust.info)

Then convert into an anchor tag with _blank target correct?

Or are we wanting to scan for anchor tags in the markdown and add a _blank?

Or is it both?

**Comment by jandrieu** [comment]
Good catch. I was thinking we do the scan in the html, which might simplify things.

I added a bunch of links to the top of the default.md for testing, including a simple .md link and fragment links in both .md and html.

Looking at the options, I think if we apply the following after converting to HTML:
1. if the link URL starts with "#", do nothing in the rendering
2. if the link URL has a target, do nothing in the rendering
3. if the link URL has no target (and is not "#"), set the target to "_blank"

Then, either on-click or on the open (where we currently intercept)
1. if the link URL has a saturn target, load it in the current document
2. if the link URL has a _saturn target, load it in a new Satyrn window
3. if the link URL is "about:blank" open in new Saturn window (without menu bar)
4. if the link URL is a fragment, just let chrome handle it (by scrolling)

My only doubt at this point is whether or not we have access to the target value in the window opener event handler or if in the pre-processing we want to hack the URL, prepending "satyrn:" or something.

This also raises the question of non-local URLs loaded by Saturn.  Other than the node_modules thing, I think it should "just work". 

Let me add a URL that points to a thing on github.

**Comment by jandrieu** [comment]
So... that adds one more thing, we should probably only *ever* try to open .md URLs in Satyrn

**Comment by wip-abramson** [comment]
Okay, I have added an extension which parses and adds the target="_blank" stuff when needed so the first part of this is done.

**Comment by wip-abramson** [comment]
I am not sure I understand how this works

```javascript
  mainWindow.webContents.on('new-window', function(e, url) {
    // about:blank is opened when creating stand-alone helper windows
    // such as for the About page and the Guide
    if(url && url !== 'about:blank') {
      e.preventDefault();
      console.log('EXTERNAL')
       shell.openExternal(url);
       return false;
      }
  });
``` 

But I think I am right in thinking that is the place we want to do the second part

**Comment by jandrieu** [comment]
Yes. That's probably where the second part happens--especially if we can get the target value in this code to put "satyrn" and "_satyrn" in the right place.  The test with the about:blank was because without it the about/guide pop-ups were being shunted to the shell, which didn't know which app to open.

However, we may need to intercept in an on-click handler on the link elements, especially if we can't get the target value in this function. I'd prefer to do it all here.

**Comment by jandrieu** [comment]
btw, that function is called whenever an explicit target is used.

Also, we need to add the check to see if the window exists already. When using a target that already exists, you get back the same window. So... when I fixed the guide code to use "guide" as the target, it re-used the same window, added the guide content again (a bug), *and* failed to bring the window to the foreground.

**Comment by wip-abramson** [comment]
I have fixed a number of these.

The styling is a bit of a fudge I have copied main.css into the app folder because I can't figure out how this css is brought in from webpack or how we can access it.

I have changed the target back to guide and fixed the re-adding content bug. You can get the target using the disposition variable in the new-window listener.

Still need to:
* Make windows focus on open
* Make target satyrn open in same window - currently still opens in browser

**Comment by wip-abramson** [comment]
Now it should be just the focus on open issue.

**Comment by wip-abramson** [comment]
Actually to clarify: The problem is focusing on the help page for example, when the help page is already open in another window. Currently it is not getting brought to the foreground.

**Comment by jandrieu** [comment]
Ok. I fixed the focus by closing the old pop-up window if it exists. I needed a timeout so we didn't close it before the IPC call gets made (closing it without the timeout throw an error). We could potentially use a nextTick or whatever, but the old trusty timeout worked great.

However, opening the .md directly, e.g.,
> satyrn target (open in current Satyrn) https://github.com/WebOfTrustInfo/satyrn/raw/master/README.md
And in a new window
> _satyrn target (open in new Satyrn window) https://github.com/WebOfTrustInfo/satyrn/raw/master/README.md

Both fail to render the .md. I think this is the last bit for this issue.

**Comment by wip-abramson** [comment]
Confused, this works for me I am pretty sure

**Comment by wip-abramson** [comment]
Last problem I can see is when target = _satyrn but the window is already open it doesn't focus on the correct window. So I assume similar fix to above @jandrieu, although this happens in background.js rather than app so it is a little different.

**Comment by jandrieu** [comment]
Hmmmm... we probably shouldn't close it, since it may have state. Also, if we are want it to be like "_blank", I think we should open it in a new window always. This might mean simply changing the target to a target 

As for the latest... yeah. I did a pull and clicking on the "satyrn" link, it just shows the markdown. *AND* we lose the ability to open new files. Opening new files simply stops doing anything. 

If I use "_satyrn", that opens a new window, but it is also both unrendered markdown. The menu functions relate to the parent window and not the new one. For example, changing the edit mode for the new window changes the edit state of the initiating document. Loading a new file loads it into the initiating window.

**Comment by wip-abramson** [comment]
Ah, my bad sorry :)

**Comment by jandrieu** [comment]
Are you able to reproduce?

**Comment by wip-abramson** [comment]
Yeah, I was just being an idiot.

**Comment by wip-abramson** [comment]
Okay, I have solved part of this although it has thrown up a number of questions and issues.

Markdown can now be rendered as markdown using the converter both in a new window and the same window as appropriate. This is done using a XmlHttpRequest to fetch the content.

Issues:

- Request assumes files are Markdown. Currently this breaks if they aren't, I have added a test url but have not dealt with this.
- For same page, the kernel.kill() function in resetKernel does not exist. I have commented this out for now but assume we need to do something here. The whole state seems to be out of sync. You can switch to edit mode, add a javascript tag and write in the editor. Running the code gives no output. But you are able to reset the editor. Needs looking into.
- For new window, the issue is that switching to edit mode changes the original window rather than the current one. This has been mentioned before.
- I have also added some todos around what file names and targets we should be giving this windows. Particularly for targets when opening a new window. These probably need to be different for each window otherwise all links will just open in the same window, but not sure how we would generate or track these. Easiest way would be to make each link click create a window with a different target so if the same link is clicked twice then two windows would open.

This is quite a lot of so may be best to open new issues individually? Let me know and I can do that.

**Comment by jandrieu** [comment]
I think we might be able to fix this if we figure out how to open a file with the app.

Then to open a _saturn window, we use the shell to open the file? We'll need to make sure we can open with the arg as a URL, but that should be straightforward.

**Comment by wip-abramson** [comment]
Okay, after chatting with @ewelton and @gannan08 today, I have had another attempt at this which I think is more along the lines of what you were thinking Joe.

I have refactored the create window code that was in app.on("ready ... into is own function. This function is now called for every _satyrn target which then adds the appropriate listeners for that window.

I have removed all references to mainWindow. We don't currently need to refer to the windows and can just use the event listeners on each window (I think).

File menus now work as expected

I have introduced a bug, reload no longer works - possibly track separately? I moved the call to load the markdown file from the app.js into background which I think is correct. However we need to make sure we are reloading the correct file on a reload event. I couldn't find this exact event handler on the window, but there must be something. Figured I would just commit and hopefully it is an easy fix I just missed. (Sorry if its not, I tried to create a new branch locally and push but not sure I have permissions). 

Finally I still use a http Request to load the url file contents before passing to converter. Not sure there is a better way than this, although it does mean the issue with a non markdown url still exists.

Open to suggestions, but to me this feels like its on the right track now.

**Comment by wip-abramson** [comment]
Fixed the reload. I am hesitantly saying this is now done although there is still the external url with satyrn target that isn't a markdown file minor issue.

**Comment by wip-abramson** [comment]
@jandrieu Can you test this again, I think we can close now.

**Comment by jandrieu** [comment]
LGTM
